insert into public.houses (code, display_name)
values
  ('MR-1', 'Mastrip Residence 1'),
  ('MR-2', 'Mastrip Residence 2'),
  ('MR-3', 'Mastrip Residence 3'),
  ('MR-4', 'Mastrip Residence 4'),
  ('MR-5', 'Mastrip Residence 5'),
  ('MR-6', 'Mastrip Residence 6'),
  ('MR-7', 'Mastrip Residence 7'),
  ('MR-8', 'Mastrip Residence 8'),
  ('MR-9', 'Mastrip Residence 9'),
  ('MR-10', 'Mastrip Residence 10'),
  ('MR-11', 'Mastrip Residence 11'),
  ('MR-12', 'Mastrip Residence 12'),
  ('MR-13', 'Mastrip Residence 13'),
  ('MR-14', 'Mastrip Residence 14'),
  ('MR-15', 'Mastrip Residence 15'),
  ('MR-16', 'Mastrip Residence 16'),
  ('MR-17', 'Mastrip Residence 17'),
  ('MR-18', 'Mastrip Residence 18'),
  ('MR-19', 'Mastrip Residence 19'),
  ('MR-20', 'Mastrip Residence 20'),
  ('MR-21', 'Mastrip Residence 21'),
  ('MR-22', 'Mastrip Residence 22'),
  ('MR-23', 'Mastrip Residence 23'),
  ('MR-24', 'Mastrip Residence 24'),
  ('MR-25', 'Mastrip Residence 25'),
  ('MR-26', 'Mastrip Residence 26'),
  ('MR-27', 'Mastrip Residence 27'),
  ('MR-28', 'Mastrip Residence 28'),
  ('MR-29', 'Mastrip Residence 29'),
  ('MR-30', 'Mastrip Residence 30'),
  ('MR-31', 'Mastrip Residence 31'),
  ('MR-32', 'Mastrip Residence 32'),
  ('MR-33', 'Mastrip Residence 33')
on conflict (code) do update
set
  display_name = excluded.display_name,
  is_active = true,
  updated_at = now();
